### ISSUE TITLE
Don't save user model correctly

### ISSUE THREAD

**Issue by fpreti** [lucafaggianelli/sails-hook-bucaniere#8]
Hi,
if I try to save a new user (but I think the update is also affected), the password is not saved correctly.
Encryption is missing, on local db i have "password": "abc123"

**Comment by lucafaggianelli** [comment]
Hi,

yeah right, the CRUD features in the admin panel are for writing directly to the DB via sails model, that is, under the hood it uses `User.create()` and I just saw that sails encrypt the password in the `api/controllers/entrance/signup.js` controller using the helper function `sails.helpers.passwords.hashPassword(inputs.password)`.

Now I see only 1 way to go if you want to use Bucaniere to edit user passwords: modify signup controller and attach a listener to User model, so when a new user is created or an existing one is edited, the password is hashed automatically, be sure to remove the hashing logic from all the user controllers. Honestly, it's strange that Sails hashes the pwd in this way.

Otherwise, you must add another section in the admin panel just to handle users.

**Comment by fpreti** [comment]
This is strange, i will search a method to solve this issue. Thanks for explain me
